name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2

      - name: zip files
        run: zip scripts.zip scripts


      - name: Create git tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: RELEASE
          git_commit_sha: ${{ github.sha }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          draft: false
          tag_name: RELEASE
          files: |
            scripts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
